import type { ProductAnalyticsRecord } from "./analytics";

// Custom environment variable declarations that augment the auto-generated Cloudflare.Env.
// (worker-configuration.d.ts is auto-generated by `wrangler types` and should not be edited.)

declare global {
  namespace Cloudflare {
    interface Env {
      // Deployment-wide admin usernames.
      ADMINS?: string[];

      // Workers AI binding (injected by generate-wrangler-prod / run-dev-server; not in base wrangler.jsonc).
      WORKERS_AI: Ai;

      // Blueprint storage bindings.
      BLUEPRINTS: KVNamespace;             // Workers KV for blueprint metadata lookup
      BLUEPRINT_CONTENT: R2Bucket;         // R2 bucket for blueprint code snapshots

      // User avatar storage.
      AVATARS: KVNamespace;                // Workers KV for user avatar images

      // Note: gatekeeper service bindings (GATEKEEPER_*) are intentionally NOT declared here. Core
      // discovers them generically by scanning env for the GATEKEEPER_ prefix (buildGatekeeperVendorMap)
      // and never references a specific gatekeeper by name, so naming one here would be wrong.

      // Optional product analytics stream. Deployments can bind this to a
      // structured Cloudflare Pipelines stream; local/dev configs omit it and analytics no-op.
      PRODUCT_ANALYTICS?: import("cloudflare:pipelines").Pipeline<ProductAnalyticsRecord>;

      // Optional browser error pipeline. Both bindings must be present before reports dispatch.
      FRONTEND_ERROR_REPORTER?: Service<
        import("@gadgets/backend-utils/error-reporting").ErrorReporter
      >;
      FRONTEND_ERROR_RATE_LIMITER?: RateLimit;

      // The Browser Run binding (BROWSER) used to render Gadget exports is intentionally NOT
      // redeclared here: wrangler's generated types make it required, and TypeScript 7 rejects
      // weakening it to optional in a merged augmentation. Self-hosted deployments may omit the
      // binding, so use sites read it as `BrowserRun | undefined` and null-check.

      // ---------------------------------------------------------------------------------------------
      // Optional features: sign-in via authentication gatekeepers. All OFF by default; existing
      // password-only deployments are unaffected. OAuth app credentials live on the gatekeeper
      // Workers, not here.
      // ---------------------------------------------------------------------------------------------

      // Comma-separated allowlist of gatekeeper vendor ids permitted to drive sign-in (e.g.
      // "google,github,cloudflare"). A listed gatekeeper must also advertise providesAuth. Empty =
      // no gatekeeper sign-in (password only).
      AUTH_GATEKEEPERS?: string;

      // Set to "true" to disable username/password login + signup (gatekeeper sign-in only). Only
      // takes effect when at least one auth gatekeeper is allowlisted (otherwise password auth stays
      // on to avoid locking everyone out).
      DISABLE_PASSWORD_AUTH?: string;

      // Public base URL of the deployment.
      PUBLIC_BASE_URL?: string;

      // The deployment's registered "Sign in with AnyRouter" OAuth client id (public; obtained
      // via AnyRouter dynamic client registration — see deploy/anyrouter-os.md). Enables the
      // authorize/consent flow that grants each user's own inference key.
      ANYROUTER_OAUTH_CLIENT_ID?: string;

      // Set to "true" (together with ANYROUTER_OAUTH_CLIENT_ID) to make "Sign in with AnyRouter"
      // the sole sign-in/sign-up method: users authenticate with their anyrouter.dev account, which
      // is also the account billed for inference. Suppresses password, gatekeeper, and Clerk
      // sign-in. Ignored unless the client id is set, so a stray flag can't lock everyone out.
      ANYROUTER_AUTH_ONLY?: string;

      // URL of a second mark shown alongside the (admin-uploaded) primary site logo as a
      // horizontal lockup, e.g. pairing a vendor mark with the default Cloudflare OS mark.
      SITE_LOGO_SECONDARY_URL?: string;

      // Deployment-wide default for AdminConfig.ambientGatekeeperModes (see provisioning-policy.ts):
      // a JSON object of vendorId -> mode, e.g. {"mcp":"enabled"}. Seeds the default for any vendor
      // the admin hasn't explicitly set from the admin panel; an explicit admin choice always wins.
      // See admin-config.ts's readAdminConfig.
      AMBIENT_GATEKEEPER_MODES?: string;
    }
  }
}
